Label(cont_f3, text="[ ", font=("Verdana", 15), justify=CENTER, bg=self.color_fondo).grid(column=1, pady=12)
        self.entry_x3 = Entry(cont_f3, validate="key", validatecommand=(validacion, '%P'))
        self.entry_x3.config(textvariable=x, font=("Verdana", 14), width=5, justify=CENTER)
        self.entry_x3.grid(column=2, pady=10)
        Label(cont_f3, text=" x + ", font=("Verdana", 15), justify=CENTER, bg=self.color_fondo).grid(column=3, pady=10)
        self.entry_y3 = Entry(cont_f3, validate="key", validatecommand=(validacion, '%P'))
        self.entry_y3.config(textvariable=y, font=("Verdana", 14), width=5, justify=CENTER)
        self.entry_y3.grid(column=4, pady=10)
        Label(cont_f3, text=" y + ", font=("Verdana", 15), justify=CENTER, bg=self.color_fondo).grid(column=5, pady=10)
        self.entry_z3 = Entry(cont_f3, validate="key", validatecommand=(validacion, '%P'))
        self.entry_z3.config(textvariable=z, font=("Verdana", 14), width=5, justify=CENTER)
        self.entry_z3.grid(column=6, pady=10)
        Label(cont_f3, text=" z =", font=("Verdana", 15), justify=CENTER, bg=self.color_fondo).grid(column=7, pady=10)
        self.entry_r3 = Entry(cont_f3, validate="key", validatecommand=(validacion, '%P'))
        self.entry_r3.config(textvariable=r, font=("Verdana", 14), width=5, justify=CENTER)
        self.entry_r3.grid(column=8, pady=10)
        Label(cont_f3, text=" ]", font=("Verdana", 15), justify=CENTER, bg=self.color_fondo).grid(column=9, pady=10)